config/routes.rb
CatanoaWeb::Application.routes.draw do

  match 'details'       => 'pages#details',       :path => 'details'
  match 'use_cases'     => 'pages#use_cases',     :path => 'individuelle_loesungen'
  match 'faq'           => 'pages#faq',           :path => 'faq'
  match 'contact'       => 'pages#contact',       :path => 'kontakt'
  match 'imprint'       => 'pages#imprint',       :path => 'impressum'

  match 'toggle_login'  => 'pages#toggle_login'
  
  root :to  => 'pages#index'
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  attr_accessible :email, :name, :remark, :company, :phone
  
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :remark
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
# encoding: utf-8
class PagesController < ApplicationController

  before_filter lambda {@navigation_item = params[:action]}
  
  def index
  end
  
  def details
  end
  
  def use_cases
  end
  
  def faq
  end
  
  def contact
    if request.post?
      @contact = Contact.new params[:contact]
      if @contact.valid?
        @contact.save
        flash[:notice] = 'Die Daten wurden gespeichert. Sie erhalten in Kürze eine Antwort zu Ihrer Kontaktanfrage.'
        ContactMailer.send_contact(@contact).deliver
        redirect_to contact_path
      else
        flash[:error] =  'Es ist ein Fehler aufgetreten: Mit * gekennzeichnete Felder sind Pflichtfelder!'
        render :contact
      end
      return 
    else
      @contact = Contact.new
    end
  end
  
  def toggle_login
    session[:login_visible] ||= false
    session[:login_visible] = !session[:login_visible] 
    render :json => {:login_visible => session[:login_visible]}
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def navigation_item(options, &block)
    css = (options[:item] == @navigation_item ? 'active' : '')
    css << ' ' + options[:class] if options[:class].present?
    css.strip!
    opts = css.present? ? {:class => css} : {}
    label = options[:label] || ''
    content_tag(:li, opts) do
      concat(link_to(label.html_safe, options[:path]) + (block_given? ? yield : ''))
    end
  end
  
  def headline(*titles)
    content_for :headline do
      tags = []
      titles.each do |t|
        tags << content_tag(:span, t)
        tags << tag(:br)
      end
      concat(tags.inject(:+))
    end 
  end
  
  def flash_message_class(type)
    case type
      when :alert
        "alert alert-error"
      when :error
        "alert alert-error"
      when :notice
        "alert alert-info"
      when :success
        "alert alert-info"
      else
        "alert #{type.to_s}"
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatanoaWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/pages.html.erb
<html>
  <head>
    <title>catanoa&#x99; - iPad und iPhone in Vertrieb und Außendienst - Lösungen für Messen, Außendienst und Verkauf</title>
    <%= stylesheet_link_tag 'application', :media => 'screen' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= yield :scripts %>
    <script type="text/javascript" src="//use.typekit.net/kmf2bix.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <% if session[:login_visible] %>
      <script type="text/javascript">
        jQuery(function($){
          $("#login_link").css({color: '#29ABE2'});
          $("#login").show();          
        });
      </script>
    <% end %>    
  <head>
  <body>
    <div class="head">
      <div class="container">
        <div class="content navigation">
          <ul>
            <%= navigation_item :label => 'Home',                    :item => 'index',      :path => root_path %>
            <%= navigation_item :label => 'Im Detail',               :item => 'details',    :path => details_path %>
            <%= navigation_item :label => 'Individuell',   :item => 'use_cases',  :path => use_cases_path %>
            <%= navigation_item :label => 'FAQ',                     :item => 'faq',        :path => faq_path %>
            <%= navigation_item :label => 'Kontakt',                 :item => 'contact',    :path => contact_path %>
            <li><a href="http://register.catanoa.com">Registrieren</a></li>
            <li><a id="login_link">Login</a></li>
            <li class="last"><a href="http://itunes.apple.com/de/app/catanoa/id477164859?mt=8" target="_blank"><img src="/appstore.png" alt="catanoa im App Store" /></a>
            <%= yield :navigation %>
          </ul>
        </div>
        
        <div class="content">
          <div class="half headline">
            <h1><%= yield :headline %></h1>
          </div>          
          
          <div class="half login" id="login">
            <div class="content">
              <p>
                <strong>Bitte melden Sie sich mit Ihren Zugangsdaten an:</strong>
              </p>
              <form class="simple_form form_vertical" action="http://admin.catanoa.com/sessions" method="post">
                <div>
                  <label>E-Mail/Subdomain:</label>
                  <input type="text" name="email" id="email">
                </div>
                <div>
                  <label>Passwort:</label>
                  <input type="password" name="password" id="password">
                </div>
                <div>
                  <input type="submit" value="Anmelden">
                </div>
              </form>
              <p class="last smalltxt">
                <!-- <a href="#">Ich habe mein Passwort vergessen</a><br/> -->
                <a href="http://register.catanoa.com">Ich möchte mich registrieren</a>
            </div>
          </div>
        </div>        
      </div>
      <div class="stage">
        <div id="slider" class="nivoSlider">
          <%= image_tag 'slider/slider01.jpg', :title => '#slider01_title', 'data-thumb'.to_sym => '/assets/slider/slider01.jpg' %>
          <%= image_tag 'slider/slider02.jpg', :title => '#slider02_title', 'data-thumb'.to_sym => '/assets/slider/slider02.jpg' %>
          <%= image_tag 'slider/slider03.jpg', :title => '#slider03_title', 'data-thumb'.to_sym => '/assets/slider/slider03.jpg' %>
          <%= image_tag 'slider/slider04.jpg', :title => '#slider04_title', 'data-thumb'.to_sym => '/assets/slider/slider04.jpg' %>
          <%= image_tag 'slider/slider05.jpg', :title => '#slider05_title', 'data-thumb'.to_sym => '/assets/slider/slider04.jpg' %>
        </div>
        <div id="slider01_title" class="nivo-html-caption">iPad - Mediathek</div>
        <div id="slider02_title" class="nivo-html-caption">iPad - Produktdetailansicht</div>
        <div id="slider03_title" class="nivo-html-caption">Browser - Redaktionssystem</div>
        <div id="slider04_title" class="nivo-html-caption">iPad - Lead-Management</div>
        <div id="slider05_title" class="nivo-html-caption">iPad - Verschiedene Kataloge</div>

        <div class="container">
          <div class="half">
            &nbsp;
          </div>
        </div>
      </div>
    </div>

    <div class="page-wrapper">
      <div class="container">
        <div class="row-fluid">
          <%= render 'pages/alerts', flash: flash %>
          <%= yield %>
        </div>
      </div>      
    </div>

    <div class="footer">
      <div class="container">
        <div class="content">
            &copy; metaminded UG (haftungsbeschränkt), provideal GmbH | <%= link_to "Kontakt", contact_path %> | <%= link_to "Impressum", imprint_path %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/_alerts.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, id: 'flash', class: flash_message_class(type) + ' alert-fade', style: 'text-align: center' do %>
    <%= message %>
  <% end %>
<% end %>

app/views/pages/contact.html.erb
<%= headline 'Kontakt' %>

 <div class="content-wrapper">
   <div class="container">
     <div class="half">
       <div class="content">
         <h1>Kontaktieren Sie uns.<br />
             Gerne stehen wir für Ihre Fragen zur Verfügung.</h1>
         <p> 
           <strong>metaminded UG (haftungsbeschränkt)</strong><br />
           Ulmer Str. 124<br />
           73431 Aalen
         </p>
         <p>
           Telefon: +49 7361 589 590 0<br />
           Telefon: +49 7361 589 590 1
         </p>
         <p>
           <a href="mailto:team@metaminded.com">team@metaminded.com</a><br />
           <a href="http://www.metaminded.com">www.metaminded.com</a>
         </p>
         
         <%= simple_form_for @contact, :url => contact_path do |f| %>
          <%= f.input :name, :label => 'Name' %>
          <%= f.input :company, :label => 'Firmenname' %>
          <%= f.input :email, :label => 'E-Mail-Adresse' %>
          <%= f.input :phone, :label => 'Telefonnummer' %>
          <%= f.input :remark, :label => 'Bemerkung', :as => :text %>
          <%= f.submit :value => 'Kontaktanfrage senden' %>
         <% end %>
       </div>
     </div>
     <div class="half">
       <div class="content">
         <h1>Es gibt im Moment in diese Mannschaft</h1>
         <p>Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind. Ich lese nicht sehr viele <strong>Zeitungen, aber ich habe gehört viele Situationen</strong>. Erstens: wir haben nicht offensiv gespielt. Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv wie Bayern. Letzte Spiel hatten wir in Platz drei Spitzen: Elber, Jancka und dann Zickler. Wir müssen nicht vergessen Zickler.</p>
         <h2>Mehmet eh mehr Basler</h2>
         <p class="last">Zickler ist eine Spitzen mehr, Mehmet eh mehr Basler. Ist klar diese Wörter, ist möglich verstehen, was ich hab gesagt? Danke. Offensiv, offensiv ist wie machen wir in Platz. Zweitens: ich habe erklärt mit diese zwei Spieler: nach Dortmund brauchen vielleicht Halbzeit Pause. Ich habe auch andere Mannschaften gesehen in Europa nach diese Mittwoch. Ich habe gesehen auch zwei Tage die Training. Ein Trainer ist nicht ein Idiot! Ein Trainer sei sehen was passieren in Platz. In diese Spiel es waren zwei, drei diese Spieler waren schwach wie eine Flasche leer! Haben Sie gesehen Mittwoch, welche Mannschaft hat gespielt Mittwoch? Hat gespielt Mehmet oder gespielt Basler oder hat gespielt Trapattoni? Diese Spieler beklagen mehr als sie spielen! Wissen Sie, warum die Italienmannschaften kaufen nicht diese Spieler? Weil wir haben gesehen viele Male solche Spiel! Haben</p>
       </div>
   </div>
 </div>
 
 <div class="content-wrapper">
   <div class="container">
     <div class="third">
       <div class="content">
         <h3>Es gibt im Moment in diese Mannschaft</h3>
         <p class="last">Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind. Ich lese nicht sehr viele Zeitungen, aber ich habe gehört viele Situationen. Erstens: wir haben nicht offensiv gespielt. Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv wie Bayern. Letzte Spiel hatten wir in Platz drei Spitzen: Elber, Jancka und dann Zickler. Wir müssen nicht vergessen Zickler.</p>
       </div>
     </div>
     <div class="third">
       <div class="content">
         <h3>Es gibt im Moment in diese Mannschaft</h3>
         <p class="last">Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind. Ich lese nicht sehr viele Zeitungen, aber ich habe gehört viele Situationen. Erstens: wir haben nicht offensiv gespielt. Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv wie Bayern. Letzte Spiel hatten wir in Platz drei Spitzen: Elber, Jancka und dann Zickler. Wir müssen nicht vergessen Zickler.</p>
       </div>
     </div>
     <div class="third">
       <div class="content">
         <h3>Es gibt im Moment in diese Mannschaft</h3>
         <p class="last">Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind. Ich lese nicht sehr viele Zeitungen, aber ich habe gehört viele Situationen. Erstens: wir haben nicht offensiv gespielt. Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv wie Bayern. Letzte Spiel hatten wir in Platz drei Spitzen: Elber, Jancka und dann Zickler. Wir müssen nicht vergessen Zickler.</p>
       </div>
     </div>
   </div>
 </div>

 <div class="content-wrapper">
   <div class="container">
     <div class="third">
       <div class="content">
          <%= image_tag 'dummy-small.jpg' %>
       </div>
     </div>
     <div class="twothird">
       <div class="content">
         <h3>Es gibt im Moment in diese Mannschaft</h3>
         <p class="last">Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind. Ich lese nicht sehr viele Zeitungen, aber ich habe gehört viele Situationen. Erstens: wir haben nicht offensiv gespielt. Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv wie Bayern. Letzte Spiel hatten wir in Platz drei Spitzen: Elber, Jancka und dann Zickler. Wir müssen nicht vergessen Zickler. Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind.</p>
       </div>
     </div>
   </div>
 </div>

<div class="content-wrapper">
   <div class="container">
     <div class="twothird">
       <div class="content">
         <h3>Es gibt im Moment in diese Mannschaft</h3>
         <p class="last">Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind. Ich lese nicht sehr viele Zeitungen, aber ich habe gehört viele Situationen. Erstens: wir haben nicht offensiv gespielt. Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv wie Bayern. Letzte Spiel hatten wir in Platz drei Spitzen: Elber, Jancka und dann Zickler. Wir müssen nicht vergessen Zickler. Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind.</p>
       </div>
     </div>
     <div class="third">
       <div class="content">
         <%= image_tag 'dummy-small.jpg' %>
       </div>
     </div>
   </div>
 </div>

app/views/pages/faq.html.erb
<%= headline 'FAQ' %>

<div class="content-wrapper">
  <div class="container">
    <div class="twothird">
      <div class="content">
        <h1>Häufig gestellte Fragen</h1>
        <p>Hier finden Sie Antworten zu Fragen rund um catanoa. Konnten Ihnen die FAQs nicht weiterhelfen, zögern Sie nicht, uns zu kontaktieren. Klicken Sie für die Antwort einfach auf die entsprechende Frage.</p>
        <div id="accordion">
        <h3><a href="#">Kann catanoa getestet werden?</a></h3>
        <div>
          <p>
            Ja, sehr gerne! Wenden Sie sich bitte per E-Mail an <a href="mailto:team@catanoa.com">team@catanoa.com</a>. Wir senden Ihnen umgehend Zugangsdaten f&uuml;r einen Demokatalog zu.<br />Vorbereitend laden Sie bitte die <a href="http://itunes.apple.com/de/app/catanoa/id477164859?mt=8" target="_blank">catanoa App</a> aus dem iTunes App Store auf Ihr iPad.
          </p>
        </div>
        <h3><a href="#">Funktioniert catanoa auch ohne Internetverbindung?</a></h3>
        <div>
          <p>
            Sie haben kein WLAN oder UMTS Netz zur Verf&uuml;gung? Kein Problem! catanoa speichert alle Daten lokal auf Ihrem iPad. Bei der n&auml;chsten M&ouml;glichkeit werden alle Daten mit dem catanoa Server synchronisiert. Das schafft Flexibilit&auml;t und maximale Datensicherheit.
          </p>
        </div>
        <h3><a href="#">Wie sehen die Lizenzmodelle von catanoa aus?</a></h3>
        <div>
          <p>
            catanoa ist als Miet- und Kaufversion erh&auml;ltlich. Bei der Mietversion bezahlen Sie monatlich einen fixen Betrag abh&auml;ngig von der Anzahl der iPads und m&uuml;ssen sich um nichts sonst k&uuml;mmern. Wir betreiben und warten die Infrastruktur und garantieren einen reibungslosen Betrieb. M&ouml;chten Sie Ihre Daten im Hause haben, spezifische Funktionen implementieren oder catanoa f&uuml;r sehr viele Nutzer zur Verf&uuml;gung stellen, bieten wir eine Enterprise- L&ouml;sung als Kaufversion an. Bitte beachten Sie, dass bei der Mietversion nicht alle individuellen Anpassungen m&ouml;glich sind. Gerne unterbreiten wir Ihnen ein Angebot.
          </p>
        </div>
        <h3><a href="#">Wie sicher sind meine Daten?</a></h3>
        <div>
          <p>
            Ihre Daten sind sicher! Wir achten auf die Vorschriften des Bundesdatenschutzgesetzes (BDSG) und Geheimhaltungsvorschriften (z.B. Par. 203 I Nr. StGB). Die Kommunikation der catanoa App mit dem catanoa Server ist &uuml;ber SSL sicher verschl&uuml;sselt. Weitere Informationen hierzu finden Sie in unseren Datenschutzbestimmungen.
          </p>
        </div>
        <h3><a href="#">&Uuml;bernehmen Sie auch das Einpflegen der Inhalte f&uuml;r mich?</a></h3>
        <div>
          <p>
            Gerne unterbreiten wir Ihnen ein Angebot zur Aufbereitung Ihrer Daten und deren Bereitstellung in catanoa.
          </p>
        </div>
        <h3><a href="#">Gibt es catanoa auch f&uuml;r das iPhone und andere Plattformen?</a></h3>
        <div>
          <p>
            Ja, es gibt eine abgespeckte Version f&uuml;r das Apple iPhone. Andere Plattformen unterst&uuml;tzen wir aus verschiedenen Gr&uuml;nden nicht. Die Vielzahl an Ger&auml;ten z.B. in der Android-Welt macht es schwierig und extrem aufw&auml;ndig, allen Herstellern und verschiedenen Softwareversionen mit gleicher Qualit&auml;t gerecht zu werden.
          </p>
        </div>
      </div> <!-- accordion end -->
      </div>
    </div>
  </div>
</div>

app/views/pages/imprint.html.erb
<%= headline 'Impressum' %>

 <div class="content-wrapper">
   <div class="container">
     <div class="twothird">
       <div class="content">
         <h1>Kontaktieren Sie uns.</h1>
         <p>Gerne stehen wir für Ihre Fragen rund um catanoa zur Verfügung.</p>
         <p>
           
        </p>
       </div>
     </div>
     <div class="third blue" style="margin-top:46px;">
       <div class="content">
         <p> 
           <strong>metaminded UG (haftungsbeschränkt)</strong><br />
           Ulmer Str. 124<br />
           73431 Aalen
         </p>
         <p>
           Telefon: +49 7361 589 590 0<br />
           Telefon: +49 7361 589 590 1
         </p>
         <p>
           <a href="mailto:team@metaminded.com">team@metaminded.com</a><br />
           <a href="http://www.metaminded.com">www.metaminded.com</a>
         </p>
       </div>
     </div>
   </div>
 </div>

app/views/pages/index.html.erb
<%= headline 'catanoa - iPad im ', 'Vertrieb und Außendienst' %>

<div class="content-wrapper">
  <div class="container">
    <div class="twothird">
      <div class="content">
        <h1>Multimediale Kataloge und Lead-Management auf dem iPad</h1>
        <p class="last">catanoa ist die Cloud-basierte iPad-Lösung für Ihren Vertrieb im Tagesgeschäft, auf Messen und Veranstaltungen. Optimieren Sie mit catanoa Ihre Distribution von Verkaufsunterlagen, setzen Sie Ihre Produkte und Dienstleistungen auf dem Trendgerät iPad in Szene und schaffen Sie effiziente Möglichkeiten zur Lead-Erfassung.<br /><br /><strong>Mobile Unternehmenslösungen mit catanoa Cloud-Services - <br />Beeindruckende Vertriebsunterstützung für Ihren Erfolg.</strong></p> 
      </div>
    </div>
    <div class="third">
      <div class="content">
        <h1>&nbsp;<br />&nbsp;</h1>
          <ul>
            <li><strong><%= link_to "Lernen Sie die Funktionen kennen", details_path %></strong></li>
            <li><%= link_to "Broschüre downloaden", '/downloads/catanoa-broschuere.pdf' %>
          </ul>
      </div>
    </div>
  </div>
</div>

<div class="content-wrapper gray">
  <div class="container blue">
    <div class="third blue">
      <div class="content">
        <h3>Jetzt 14 Tage kostenlos testen</h3>
        <p class="last">Testen Sie catanoa Cloud kostenlos und unverbindlich 14 Tage lang. <br /><br /><strong><a href="http://register.catanoa.com">Jetzt registrieren</a></strong></p>
      </div>
    </div>
    <div class="third">
      <div class="content">
        <h3>Broschüre downloaden</h3>
        <p class="last">Laden Sie <%= link_to "hier", '/downloads/catanoa-broschuere.pdf' %> die catanoa Produktbroschüre als PDF Datei herunter. Gerne übersenden wir diese auch <%= link_to "per Post", contact_path %> an Sie.</p>
      </div>
    </div>
    <div class="third blue">
      <div class="content">
        <h3>Sie haben Fragen?</h3>
        <p class="last">Wir die Antworten! Kontaktieren Sie uns gerne telefonisch unter:<br /><br />
          <strong>+49 7361 589 590 0</strong></p>
      </div>
    </div>
  </div>

app/views/pages/use_cases.html.erb
<%= headline 'Individuelle', 'Lösungen' %>

<div class="content-wrapper">
  <div class="container">
    <div class="twothird">
      <div class="content">
        <h1>Individuelle Lösungen - <br />auf Ihr Unternehmen maßgeschneidert</h1>
        <p>Anforderungen an die Werkzeuge im Vertriebsalltag sind oft ähnlich aber eben auch ebenso häufig sehr unterschiedlich.</p>
        <h2>Praxiserprobter Werkzeugkasten</h2>
        <p>Für wiederkehrende Anforderungen im Vertriebsalltag halten wir eine Reihe von Werkzeugen als Baukastensystem bereit. So können wir bei multimedialen Produktkatalogen, zentral verwalteten Salesfoldern und Verkaufsunterlagen oder einer Lösung zur Lead-Erfassung auf Messen auf vielfach praxiserprobte Module zurückgreifen. Nach wenigen Anpassungen sind diese schnell und umkompliziert in Ihre Vertriebsarbeit integriert.</p>
        <h2>Individuelle Lösungen & Entwicklung</h2>
        <p class="last">Auf Basis von catanoa bieten wir individuelle Lösungen und Entwicklung an. Sei es z.B. die Anbindung an ein bestehendes Warenwirtschaftssystem oder an ein eCommerce System - durch eine offene Architektur und universelle Schnittstellen sind wir in der Lage nahezu jeder Anforderung gerecht zu werden und Ihren Mitarbeitern die richtigen Werkzeuge an die Hand zu geben. Wir finden gemeinsam die passende Lösung - perfekt geplant, integriert und absolut passend für Ihr Unternehmen und Ihre Anforderungen.</p>
      </div>
    </div>
    <div class="third">
      <div class="content">
        &nbsp;
      </div>
  </div>
</div>